[build]
builder = "nixpacks"
buildCommand = """
  python -m pip install --upgrade pip && \
  cd backend && \
  pip install -r requirements.txt && \
  pip install -e .
"""

[deploy]
startCommand = "cd backend && python3 -m uvicorn src.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 120

[service]
autoDeploy = false

[mounts]
source = "/data"
destination = "/tmp/lancedb"

# Add Python configuration
[build.env]
NIXPACKS_PYTHON_VERSION = "3.10.0"
PYTHONPATH = "/app/backend"