[build]
builder = "nixpacks"
buildCommand = """
cd backend && \
apt-get update && \
apt-get install -y python3 python3-pip && \
python3 --version && \
pip install -r requirements.txt && \
pip install -e . && \
cd .. && \
mkdir -p /app/backend/data/processed && \
cp -r data/* /app/backend/data/ && \
which uvicorn  # Print uvicorn location
"""

[deploy]
# Use full path to Python and install location
startCommand = """
cd backend && \
export PATH="/usr/local/bin:$PATH" && \
which uvicorn && \
PYTHONPATH=/app/backend python3 -m uvicorn src.main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 120
"""
healthcheckPath = "/api/v1/health"
restartPolicyType = "on_failure"
healthcheckTimeout = 120
healthcheckInterval = 45
startupTimeout = "5m"

[nixpacks]
python_version = "3.10"

[[build.env]]
name = "PYTHONPATH"
value = "/app/backend"

[[build.env]]
name = "DATA_DIR"
value = "/app/backend/data"

[[build.env]]
name = "PATH"
value = "/usr/local/bin:$PATH"