[build]
builder = "nixpacks"
buildCommand = "cd backend && pip install -r requirements.txt && pip install -e ."

[deploy]
startCommand = "cd backend && python3 -m uvicorn src.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 120

[service]
autoDeploy = false

[mounts]
source = "/data"
destination = "/tmp/lancedb"