services:
  - type: web
    name: asksunna-backend
    env: python
    plan: free
    region: oregon
    buildCommand: |
      # Install Python dependencies
      cd backend && \
      pip install -r requirements.txt && \
      pip install -e .
      
      # Create necessary directories
      mkdir -p /opt/render/project/src/backend/data/processed
      mkdir -p /tmp/lancedb
      chmod 777 /tmp/lancedb
      
      # Copy data files to correct location
      cp -r data/* /opt/render/project/src/backend/data/
    
    startCommand: cd backend && LANCEDB_CONFIG_DIR=/tmp/lancedb python3 -m uvicorn src.main:app --host 0.0.0.0 --port $PORT
    
    # Optimize for free tier
    autoDeploy: false
    healthCheckPath: /api/v1/health
    healthCheckTimeout: 100
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
      - key: DATA_DIR
        value: /opt/render/project/src/backend/data
      - key: RENDER
        value: "true"
      - key: ALLOWED_ORIGINS
        sync: false
      - key: GOOGLE_API_KEY
        sync: false