name: asksunna
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - pip:
    - fastapi==0.109.2
    - uvicorn==0.27.1
    - python-dotenv==1.0.1
    - sentence-transformers==2.2.2
    - huggingface-hub==0.19.4
    - transformers>=4.36.2
    - lancedb==0.4.0
    - google-generativeai==0.3.2
    - pydantic==2.6.1